name: Build
on:
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
      - 
        name: Build Passt
        run: |
          #!/bin/bash
          cd "$GITHUB_WORKSPACE"
          make pkgs
